announce = false
token = '19ea4a55-6a48-43b3-b20a-2897a026c95c'

description = 'test'
website = 'test.com'
gamemode = 'Freeroam'

language = 'en'
modules = [ 'js-module-v2' ]
name = 'TestServer'
players = 4096
port = 7788
tags = [ 'customTag1', 'customTag2', 'customTag3', 'customTag4' ]
disableOptionalProps = true
connectionQueue = false
useEarlyAuth = true
earyAuthUrl = 'http://localhost:3000/earlyauth'

resources = [
    'wasteland-assets',
    'bodies',
    #    'hallo',
    'core'
]

# Turn this off in production mode
debug = true

# Leave host as 0.0.0.0, don't change it.
host = '0.0.0.0'

mapBoundsMinX = -10000
mapBoundsMinY = -10000
mapBoundsMaxX = 65536
mapBoundsMaxY = 65536
mapCellAreaSize = 1000

[js-module]
global-webcrypto = true
global-fetch = true

[antiCheat]
# Enables server-side weapon checks
# For example, if a weapon is given via giveWeaponToPed native it won't be synced
weaponSwitch = true
# Enables collision checks so natives like setEntityNoCollisionEntity will not work
collision = true