type = 'jsv2'
main = 'server/startup.js'
client-files = [ 'client/*', 'shared/*' ]
client-main = 'client/startup.js'
deps = []
required-permissions = [
    "Screen Capture",
    "WebRTC",
    "Clipboard Access",
    "Extended Voice API"
]